name: Build

on:
  workflow_dispatch

env:
  NODE: 18

jobs:
  build:
    name: Build Icons
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE }}"
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - name: build icons
        run: npm run build
      - name: Commit Icons
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git checkout -b "actions/new-icons"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push --set-upstream origin actions/new-icons
          gh pr create --title "🤖: Adding new icons" --body "This adds the latest icons from lucide" -r @grimlink -B main
